server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 200 #初始连接
    max-active: 1000  #最大连接数
    min-idle: 50  #保持最小连接数
    max-wait: 60000  #获取连接,超时时间
    time-between-eviction-runs-millis: 2000  #监测空闲连接,时间间隔
    max-evictable-idle-time-millis: 900000  #连接最大生存时间
    min-evictable-idle-time-millis: 600000  #连接最小生存时间
    testWhileIdle: true
    testOnBorrow: false                            #获取连接时执行检测，建议关闭，影响性能
    testOnReturn: false                            #归还连接时执行检测，建议关闭，影响性能
    poolPreparedStatements: false
    keep-alive: true
    druid:
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: ahzrNYPGwL1gaLxWIkeHRM5tgUe1uO53Qaeh9sGrIFX8A0EHdrdlTTbjs1ULROWV/NjH/mMOnHYBkdLzGn2rTg==
      filter:
        config:
          enabled: true
      connect-properties:
        config.decrypt: true
        config:
          decrypt:
            key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALyYwm9JEZWDJE8n9xTXgPUBSD5gVrc+BctinENDQ6ClOlSKkl/bmDIfn39dDPbNcZjt4XciuKiPX+LMgicbNK8CAwEAAQ==
    filter:
      stat:
        slow-sql-millis: 10000  #慢sql，10s以上
        log-slow-sql: true
  sleuth:
    sampler:
      rate: 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 0   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5   # 连接池中的最大空闲连接
        min-idle: 1    # 连接池中的最小空闲连接
    timeout: 1000  #毫秒

logging:
  file:
    path: D:\logs\

permit:
  urls:
    - /sys-user/login
    - /sys-user/test